apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: default
  labels:
    app: mysql

spec:
  selector:
    app: mysql
  ports:
    - port: 3306
  # By default, when you create a Kubernetes Service, it is assigned a cluster IP address, which provides
  # a stable endpoint for accessing the Service within the cluster.
  # However, in certain scenarios, you may not require a cluster IP and instead want direct access to individual
  # Pods associated with the Service. The Service acts as a DNS entry rather than a Load Balancer. Instead of
  # routing traffic through a single IP address, Kubernetes performs DNS-based service discovery, allowing you to
  # directly access the individual Pods associated with the Service.
  # This type of Service is then called headless Service.
  clusterIP: None
