apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: default
  labels:
    app: mysql

spec:
  replicas: 1
  strategy:
    # Old pods are first terminated, and then the new pods are created to replace them.
    # Don't use this in production scenarios.
    type: Recreate
  selector:
    matchLabels:
      app: mysql

  # Pod specification.
  # You can connect to this pod using the command -
  # kubectl run -it --rm --image=mysql:5.6 --restart=Never mysql-client -- mysql -h mysql -ppassword.
  template:
    metadata:
      labels:
        app: mysql
    spec:
      volumes:
        - name: mysql
          persistentVolumeClaim:
            claimName: mysql
        - name: users-db-creator
          configMap:
            name: users-db-creator
      containers:
        - name: mysql
          image: mysql:5.6
          resources:
            limits:
              memory: 500Mi
              cpu: 500m
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: password
          volumeMounts:
            - name: mysql
              mountPath: /var/lib/mysql
            - name: users-db-creator
              mountPath: /docker-entrypoint-initdb.d
          ports:
            - name: mysql
              containerPort: 3306
