apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql
  namespace: default

spec:
  storageClassName: default-with-retention
  resources:
    requests:
      storage: 100Mi
  accessModes:
  - ReadWriteOnce
