apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt
  namespace: default

spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: archismanmridha12345@gmail.com

    # Name of the secret used to store the ACME account private key
    privateKeySecretRef:
      name: letsencrypt

    solvers:
      - http01:
          ingress:
            class: nginx
