apiVersion: v1
kind: Service
metadata:
  name: user-management
  namespace: default
  labels:
    app: user-management

spec:
  type: LoadBalancer
  selector:
    app: user-management
  ports:
    - port: 80
      targetPort: 8080
