apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: main
  namespace: default
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt

spec:
  defaultBackend:
    service:
      name: nginx
      port:
        number: 80
  rules:
    - host: aks-masterclass.projectsofarchi.live
      http:
        paths:
          - pathType: Exact
            path: /whoami
            backend:
              service:
                name: whoami
                port:
                  number: 80
  tls:
    - hosts:
        - aks-masterclass.projectsofarchi.live
      secretName: whomai-tls
