apiVersion: apps/v1
kind: Deployment
metadata:
  name: whoami
  namespace: default
  labels:
    app: whoami

spec:
  replicas: 2
  selector:
    matchLabels:
      app: whoami

  # Pod specification.
  template:
    metadata:
      labels:
        app: whoami
    spec:
      containers:
        - name: whoami
          image: traefik/whoami:latest
          resources:
            limits:
              memory: 120Mi
              cpu: 100m
          ports:
            - containerPort: 80
